//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primeravancefinal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("primeravancefinal.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Ciudad.
        /// </summary>
        internal static string ButtonAddCity {
            get {
                return ResourceManager.GetString("ButtonAddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta alterna.
        /// </summary>
        internal static string ButtonAlternateRoute {
            get {
                return ResourceManager.GetString("ButtonAlternateRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Ciudad.
        /// </summary>
        internal static string ButtonRemoveCity {
            get {
                return ResourceManager.GetString("ButtonRemoveCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta más corta.
        /// </summary>
        internal static string ButtonShortestRoute {
            get {
                return ResourceManager.GetString("ButtonShortestRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Ciudad.
        /// </summary>
        internal static string ButtonUpdateCity {
            get {
                return ResourceManager.GetString("ButtonUpdateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        internal static string ComboBoxEnglish {
            get {
                return ResourceManager.GetString("ComboBoxEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string ComboBoxSpanish {
            get {
                return ResourceManager.GetString("ComboBoxSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        internal static string LabelCost {
            get {
                return ResourceManager.GetString("LabelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia.
        /// </summary>
        internal static string LabelDistance {
            get {
                return ResourceManager.GetString("LabelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad donde termina
        ///.
        /// </summary>
        internal static string LabelEndCity {
            get {
                return ResourceManager.GetString("LabelEndCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad de inicio.
        /// </summary>
        internal static string LabelStartCity {
            get {
                return ResourceManager.GetString("LabelStartCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo.
        /// </summary>
        internal static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio de Transporte.
        /// </summary>
        internal static string LabelTransportMode {
            get {
                return ResourceManager.GetString("LabelTransportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad agregada correctamente.
        /// </summary>
        internal static string MessageCityAdded {
            get {
                return ResourceManager.GetString("MessageCityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad eliminada correctamente.
        /// </summary>
        internal static string MessageCityRemoved_ {
            get {
                return ResourceManager.GetString("MessageCityRemoved ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma cambiado a {0}.
        /// </summary>
        internal static string MessageLanguageChanged {
            get {
                return ResourceManager.GetString("MessageLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ruta encontrada.
        /// </summary>
        internal static string MessageRouteFound {
            get {
                return ResourceManager.GetString("MessageRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe una ruta entre las ciudades.
        /// </summary>
        internal static string MessageRouteNotFound {
            get {
                return ResourceManager.GetString("MessageRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planeador de Viajes.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto rentado.
        /// </summary>
        internal static string RadioButtonCar {
            get {
                return ResourceManager.GetString("RadioButtonCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte público.
        /// </summary>
        internal static string RadioButtonPublic {
            get {
                return ResourceManager.GetString("RadioButtonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string TabExit {
            get {
                return ResourceManager.GetString("TabExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string TabInformation {
            get {
                return ResourceManager.GetString("TabInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string TabLanguage {
            get {
                return ResourceManager.GetString("TabLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        internal static string TabMap_ {
            get {
                return ResourceManager.GetString("TabMap ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsquedas.
        /// </summary>
        internal static string TabSearch {
            get {
                return ResourceManager.GetString("TabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión 1.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
