//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primeravancefinal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("primeravancefinal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add City.
        /// </summary>
        internal static string ButtonAddCity {
            get {
                return ResourceManager.GetString("ButtonAddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Route.
        /// </summary>
        internal static string ButtonAlternateRoute {
            get {
                return ResourceManager.GetString("ButtonAlternateRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove City.
        /// </summary>
        internal static string ButtonRemoveCity {
            get {
                return ResourceManager.GetString("ButtonRemoveCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest Route.
        /// </summary>
        internal static string ButtonShortestRoute {
            get {
                return ResourceManager.GetString("ButtonShortestRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify City.
        /// </summary>
        internal static string ButtonUpdateCity {
            get {
                return ResourceManager.GetString("ButtonUpdateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ComboBoxEnglish {
            get {
                return ResourceManager.GetString("ComboBoxEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string ComboBoxSpanish {
            get {
                return ResourceManager.GetString("ComboBoxSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string LabelCost {
            get {
                return ResourceManager.GetString("LabelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string LabelDistance {
            get {
                return ResourceManager.GetString("LabelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End City
        ///.
        /// </summary>
        internal static string LabelEndCity {
            get {
                return ResourceManager.GetString("LabelEndCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start City.
        /// </summary>
        internal static string LabelStartCity {
            get {
                return ResourceManager.GetString("LabelStartCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Mode.
        /// </summary>
        internal static string LabelTransportMode {
            get {
                return ResourceManager.GetString("LabelTransportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City added successfully.
        /// </summary>
        internal static string MessageCityAdded {
            get {
                return ResourceManager.GetString("MessageCityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City removed successfully.
        /// </summary>
        internal static string MessageCityRemoved_ {
            get {
                return ResourceManager.GetString("MessageCityRemoved ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to {0}.
        /// </summary>
        internal static string MessageLanguageChanged {
            get {
                return ResourceManager.GetString("MessageLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route founded.
        /// </summary>
        internal static string MessageRouteFound {
            get {
                return ResourceManager.GetString("MessageRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route exists between the cities.
        /// </summary>
        internal static string MessageRouteNotFound {
            get {
                return ResourceManager.GetString("MessageRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Planner.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented Car
        ///.
        /// </summary>
        internal static string RadioButtonCar {
            get {
                return ResourceManager.GetString("RadioButtonCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Public Transport.
        /// </summary>
        internal static string RadioButtonPublic {
            get {
                return ResourceManager.GetString("RadioButtonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TabExit {
            get {
                return ResourceManager.GetString("TabExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TabInformation {
            get {
                return ResourceManager.GetString("TabInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string TabLanguage {
            get {
                return ResourceManager.GetString("TabLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string TabMap_ {
            get {
                return ResourceManager.GetString("TabMap ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TabSearch {
            get {
                return ResourceManager.GetString("TabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
